"""Add claim_password column to Tags

Revision ID: 5f4b8d32249d
Revises: b9a0829b5384
Create Date: 2024-10-17 20:54:58.479551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4b8d32249d'
down_revision = 'b9a0829b5384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('claim_password')

    # ### end Alembic commands ###
